export declare function isActualNaN<T> (value:any):boolean;
export declare function isType<T>(value:any, type:string):boolean;
export declare function isA<T>(value:any, type:string):boolean;
export declare function isDefined<T> (value:any):boolean;
export declare function isEmptyString<T>(value:any, trimmed:boolean ):boolean;
export declare function isEmpty<T>(value:any):boolean;
export declare function isEqual<T>(value:any, other:any):boolean;
export declare function isHosted<T> (value:any, host:any):boolean;
export declare function isInstance<T> (value:any, constructor:any):boolean;
export declare function isInstanceOf<T> (value:any, constructor:any):boolean;
export declare function isNull<T> (value:any):boolean;
export declare function isNil<T> (value:any):boolean;
export declare function isUndefined<T> (value:any):boolean;
export declare function isUndef<T> (value:any):boolean;
export declare function isArguments<T> (value:any):boolean;
export declare function isArray<T>(value:any):boolean;
export declare function isArgumentsEmpty<T> (value:any):boolean;
export declare function isEmptyArguments<T> (value:any):boolean;
export declare function isEmptyArray<T>(value:any):boolean;
export declare function isArrayEmpty<T>(value:any):boolean;
export declare function isArrayLike<T> (value:any):boolean;
export declare function isBool<T> (value:any):boolean;
export declare function isBoolean<T> (value:any):boolean;
export declare function isFalse<T>(value:any):boolean;
export declare function isTrue<T>(value:any):boolean;
export declare function isDate<T>(value:any):boolean;
export declare function isDateValid<T>(value:any):boolean;
export declare function isValidDate<T>(value:any):boolean;
export declare function isElement<T> (value:any):boolean;
export declare function isError<T> (value:any):boolean;
export declare function isFunction<T> (value:any):boolean;
export declare function isFn<T> (value:any):boolean;
export declare function isNumber<T> (value:any):boolean;
export declare function isInfinite<T> (value:any):boolean;
export declare function isDecimal<T> (value:any):boolean;
export declare function isDivisibleBy<T> (value:any, n:number):boolean;
export declare function isInt<T> (value:any):boolean;
export declare function isInteger<T> (value:any):boolean;
export declare function isMaximum<T> (value:any, others:any[]):boolean;
export declare function isMinimum<T> (value:any, others:any[]):boolean;
export declare function isNaN<T> (value:any):boolean;
export declare function isEven<T>(value:any):boolean;
export declare function isOdd<T> (value:any):boolean;
export declare function isGe<T> (value:any,other:any):boolean;
export declare function isGt<T> (value:any,other:any):boolean;
export declare function isLe<T>(value:any,other:any):boolean;
export declare function isLt<T> (value:any,other:any):boolean;
export declare function isWithin<T> (value:number, start:number, finish:number):boolean;
export declare function isObject<T>(value:any):boolean;
export declare function isEmptyObject<T>(value:any):boolean;
export declare function isPrimitive<T>(value:any):boolean;
export declare function isHash<T>(value:any):boolean;
export declare function isRegexp<T> (value:any):boolean;
export declare function isString<T> (value:any):boolean;
export declare function isStringEmpty<T>(value:any):boolean;
export declare function isBase64<T> (value:any):boolean;
export declare function isHex<T>(value:any):boolean;
export declare function isSymbol<T> (value:any):boolean;
export declare function isBigInt<T> (value:any):boolean;
export declare function isJSON<T> (value:any):boolean;
