export declare function clean <T>(object: T, options?: CleanOptions): Partial<T>;

export type CleanOptions = {
    config: undefined | "default" | "json";
    configId: undefined | "default" | "json";
    keys: string[];
    values: any[],
    // isActualNaN:boolean;
    isNaN:boolean;
    isType:boolean;
    isEqual:boolean;
    isNull:boolean;
    isUndefined:boolean;
    isError:boolean;
    isFunction:boolean;
    isFn:boolean;
    isEmpty:boolean;
    isEmptyArray:boolean;
    isEmptyObject:boolean;
    isEmptyString:boolean;
    // isNil:boolean;
    // isUndef:boolean;
    // isInfinite:boolean;
    // isArray:boolean;
    // isHosted:boolean;
    // isInstance:boolean;
    // isInstanceOf:boolean;
    // isArguments:boolean;
    // isArgumentsEmpty:boolean;
    // isEmptyArguments:boolean;
    // isArrayEmpty:boolean;
    // isArrayLike:boolean;
    // isBool:boolean;
    // isBoolean:boolean;
    // isFalse:boolean;
    // isTrue:boolean;
    // isDate:boolean;
    // isValidDate:boolean;
    // isDateValid:boolean;
    // isElement:boolean;
    // isNumber:boolean;
    // isDecimal:boolean;
    // isDivisibleBy:boolean;
    // isInt:boolean;
    // isInteger:boolean;
    // isMaximum:boolean;
    // isMinimum:boolean;
    // isEven:boolean;
    // isOdd:boolean;
    // isGe:boolean;
    // isGt:boolean;
    // isLe:boolean;
    // isLt:boolean;
    // isWithin:boolean;
    // isObject:boolean;
    // isPrimitive:boolean;
    // isHash:boolean;
    // isRegexp:boolean;
    // isString:boolean;
    // isStringEmpty:boolean;
    // isBase64:boolean;
    // isHex:boolean;
    // isSymbol:boolean;
    // isBigInt:boolean;

}
